#!/usr/bin/env python3
"""Generate the site's brand outputs from the active client's declarations.

Reads the one active `branding/<client>/` directory and writes two generated
files that Eleventy consumes:

  brand.yaml  ->  src/css/brand.css      the :root colour custom properties
  site.yaml   ->  src/_data/site.json    the site's URL, timezone, contact,
                                          and social data

Keeping these declarative rather than hard-coded is what lets a client rebrand
by editing data, and keeps the template files (home.css, the layouts) byte-
identical to canonical so `git merge upstream` stays clean.

Client discovery: the client directory is named for the client (e.g.
`branding/theblnkstudio.com/`), so the script does not hard-code a path. It
globs `branding/*/`, ignores any `_`-prefixed directory (branding/_template),
and expects exactly one active client. Zero or many is an error.

site.json compatibility: the generated JSON keeps the flat `contact` keys the
templates read today (email, phoneDisplay, phoneHref, and — for back-compat —
whatsapp, instagram, instagramHandle derived from the social map), and adds a
`social` map the footer renders generically. site.yaml is authored as `contact`
plus `social`; the generator bridges the two shapes.

Usage:
    python3 scripts/branding/build-brand.py            # auto-discovers the client
    python3 scripts/branding/build-brand.py --dry-run  # print, write nothing

Dependency: PyYAML (`pip install pyyaml`). Standard library otherwise.

Re-run whenever brand.yaml or site.yaml changes, then commit the regenerated
brand.css and site.json.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit(
        "This script needs PyYAML. Install it with:\n"
        "    pip install pyyaml\n"
        "(or: pip install --break-system-packages pyyaml on a managed system)"
    )

# scripts/branding/build-brand.py -> repo root is three directories up.
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

CSS_OUTPUT = os.path.join(ROOT, "src", "css", "brand.css")
SITE_OUTPUT = os.path.join(ROOT, "src", "_data", "site.json")


def find_client_dir() -> str:
    """Return the one active client directory, or exit with a clear error.

    A directory whose name starts with '_' (branding/_template) is a seed and is
    skipped, so only a real client directory counts.
    """
    dirs = [
        d
        for d in glob.glob(os.path.join(ROOT, "branding", "*"))
        if os.path.isdir(d) and not os.path.basename(d).startswith("_")
    ]
    if not dirs:
        sys.exit(
            "No client directory found. Expected exactly one branding/<client>/ "
            "(directories starting with '_' are ignored). Run the new-client "
            "scaffold, or add one."
        )
    if len(dirs) > 1:
        names = ", ".join(sorted(os.path.basename(d) for d in dirs))
        sys.exit(
            f"Ambiguous client: found several directories ({names}). Exactly one "
            "un-prefixed branding/<client>/ is allowed; prefix templates and "
            "demos with '_'."
        )
    return dirs[0]


# ── brand.yaml -> brand.css ──────────────────────────────────────────────────

def flatten(colors: dict) -> list:
    """Turn the `colors` mapping into ordered (group, name, value) rows.

    Supports the grouped form used in brand.yaml, where each key under `colors`
    is a group (`brand`, `surfaces`, …) whose entries are token -> value. A flat
    mapping of token -> value is also accepted, under an unnamed group.
    """
    rows = []
    for group, entries in colors.items():
        if isinstance(entries, dict):
            for name, value in entries.items():
                rows.append((group, name, str(value)))
        else:
            rows.append(("", group, str(entries)))
    return rows


def render_css(rows: list) -> str:
    """Render the (group, name, value) rows into a :root stylesheet."""
    header = (
        "/* GENERATED by scripts/branding/build-brand.py from "
        "branding/<client>/brand.yaml — do not edit by hand.\n"
        "   Re-run the script (or `npm run build:brand`) to regenerate. These are\n"
        "   the site's brand colours, the custom properties src/css/home.css\n"
        "   consumes; home.css keeps the type and layout tokens. */\n\n"
    )
    lines = [":root {"]
    last_group = None
    for group, name, value in rows:
        if group != last_group:
            if last_group is not None:
                lines.append("")
            if group:
                lines.append(f"  /* {group} */")
            last_group = group
        lines.append(f"  --{name}: {value};")
    lines.append("}")
    return header + "\n".join(lines) + "\n"


# ── site.yaml -> site.json ───────────────────────────────────────────────────

def render_site(cfg: dict) -> str:
    """Render site.yaml into the site.json shape Eleventy and the templates read.

    The `contact` block keeps the flat keys the templates use today, and gains
    back-compat `whatsapp`, `instagram`, and `instagramHandle` derived from the
    social map so nothing that still reads `site.contact.<network>` breaks. The
    `social` map is what the footer iterates to render present accounts.
    """
    contact_in = cfg.get("contact", {}) or {}
    social_in = cfg.get("social", {}) or {}

    contact = {
        "email": contact_in.get("email"),
        "phoneDisplay": contact_in.get("phoneDisplay"),
        "phoneHref": contact_in.get("phoneHref"),
    }
    # Back-compat flat keys for the two networks the templates named directly.
    if "whatsapp" in social_in:
        contact["whatsapp"] = social_in["whatsapp"]["url"]
    if "instagram" in social_in:
        contact["instagram"] = social_in["instagram"]["url"]
        contact["instagramHandle"] = social_in["instagram"].get("label")

    social = {
        name: {"url": s["url"], "label": s.get("label", name)}
        for name, s in social_in.items()
    }

    # Logo/favicon paths, so a client can use any filename or format (SVG, PNG,
    # …) instead of the fixed .png slots the template once hard-coded.
    logos_in = cfg.get("logos") or {}
    logos = {
        "dark": logos_in.get("dark", "/assets/logo-lockup-dark.png"),
        "light": logos_in.get("light", "/assets/logo-lockup.png"),
        "favicon": logos_in.get("favicon", "/assets/favicon.png"),
    }

    out = {
        "url": cfg["url"],
        "publicationTimeZone": cfg["publicationTimeZone"],
        "logos": logos,
        "contact": contact,
        "social": social,
    }
    return json.dumps(out, indent=2, ensure_ascii=False) + "\n"


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate src/css/brand.css and src/_data/site.json from the "
                    "active client's brand.yaml and site.yaml."
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="print what would be written, and write nothing",
    )
    args = ap.parse_args()

    client_dir = find_client_dir()
    client = os.path.basename(client_dir)

    brand_yaml = os.path.join(client_dir, "brand.yaml")
    site_yaml = os.path.join(client_dir, "site.yaml")

    # brand.yaml is required; site.yaml is optional (a client may not have
    # consolidated its site config yet).
    if not os.path.isfile(brand_yaml):
        sys.exit(f"{brand_yaml} not found; the client has no brand.yaml.")
    with open(brand_yaml, "r", encoding="utf-8") as fh:
        brand_cfg = yaml.safe_load(fh) or {}
    colors = brand_cfg.get("colors")
    if not colors:
        sys.exit(f"{brand_yaml} has no `colors:` block to render.")
    css = render_css(flatten(colors))

    site_json = None
    if os.path.isfile(site_yaml):
        with open(site_yaml, "r", encoding="utf-8") as fh:
            site_cfg = yaml.safe_load(fh) or {}
        site_json = render_site(site_cfg)

    if args.dry_run:
        print(f"# would write src/css/brand.css from branding/{client}/brand.yaml\n")
        print(css)
        if site_json is not None:
            print(f"# would write src/_data/site.json from branding/{client}/site.yaml\n")
            print(site_json)
        return

    os.makedirs(os.path.dirname(CSS_OUTPUT), exist_ok=True)
    with open(CSS_OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(css)
    count = sum(1 for _ in flatten(colors))
    print(f"Wrote src/css/brand.css with {count} colour tokens from branding/{client}/brand.yaml.")

    if site_json is not None:
        os.makedirs(os.path.dirname(SITE_OUTPUT), exist_ok=True)
        with open(SITE_OUTPUT, "w", encoding="utf-8") as fh:
            fh.write(site_json)
        print(f"Wrote src/_data/site.json from branding/{client}/site.yaml.")


if __name__ == "__main__":
    main()
